import { ArrowUpRight, BrainCircuit, CircleAlert, Gauge, ShieldAlert, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useGetDashboardSummary, useListAlerts, useListInsights, getGetDashboardSummaryQueryKey } from '@workspace/api-client-react';
import { ErrorBlock, EmptyBlock, formatTime, LoadingBlock, PageTitle, severityClass, Skeleton, Surface } from '@/components/ui-kit';

const trend = [{ t: '00:00', v: 8 }, { t: '04:00', v: 11 }, { t: '08:00', v: 18 }, { t: '12:00', v: 14 }, { t: '16:00', v: 27 }, { t: '20:00', v: 21 }, { t: 'Now', v: 32 }];

export default function Overview() {
  const summary = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey() } });
  const alerts = useListAlerts({ limit: 6 }, { query: { queryKey: ['/api/alerts', { limit: 6 }] } });
  const insights = useListInsights({ limit: 3 }, { query: { queryKey: ['/api/insights', { limit: 3 }] } });
  return <div className="animate-rise">
    <PageTitle eyebrow="Command center / live posture" title="Security overview" description="A fast read on what changed across your local sensor network." action={<Link href="/snort" data-testid="link-review-alerts" className="inline-flex items-center gap-2 rounded-lg bg-violet-500 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-violet-500/20 transition hover:bg-violet-400">Review alert feed <ArrowUpRight size={15} /></Link>} />
    {summary.isLoading ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(i => <Skeleton key={i} className="h-32" />)}</div> : summary.isError ? <ErrorBlock retry={() => summary.refetch()} /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <Metric label="Total detections" value={summary.data?.totalAlerts ?? 0} note="all time" icon={CircleAlert} color="violet" />
      <Metric label="High priority" value={summary.data?.highSeverity ?? 0} note="needs triage" icon={ShieldAlert} color="rose" />
      <Metric label="AI analyzed" value={summary.data?.analyzed ?? 0} note={`${summary.data?.insights ?? 0} insights generated`} icon={BrainCircuit} color="sky" />
      <Metric label="Mean risk score" value={`${summary.data?.avgRiskScore ?? 0}`} note={`${Math.round((summary.data?.avgConfidence ?? 0) * 100)}% confidence`} icon={Gauge} color="emerald" />
    </div>}
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]">
      <Surface className="p-5"><div className="mb-5 flex items-start justify-between"><div><div className="text-sm font-bold">Detection velocity</div><div className="mt-1 text-xs text-slate-500">Alerts observed over the last 24 hours</div></div><span className="rounded-md border border-emerald-400/20 bg-emerald-400/5 px-2 py-1 font-mono text-[10px] text-emerald-300">LIVE</span></div><div className="h-64">{<ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="purpleArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a78bfa" stopOpacity={.32}/><stop offset="100%" stopColor="#a78bfa" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#253044" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="t" tick={{ fill: '#64748b', fontSize: 10 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: '#64748b', fontSize: 10 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: '#111827', border: '1px solid #334155', borderRadius: 10, color: '#e2e8f0', fontSize: 12 }} /><Area type="monotone" dataKey="v" stroke="#a78bfa" strokeWidth={2} fill="url(#purpleArea)" /></AreaChart></ResponsiveContainer>}</div></Surface>
      <Surface className="p-5"><div className="mb-5 flex items-center justify-between"><div><div className="text-sm font-bold">Severity distribution</div><div className="mt-1 text-xs text-slate-500">Current alert inventory</div></div><Sparkles size={16} className="text-fuchsia-300" /></div><div className="space-y-4">{['critical','high','medium','low'].map((key) => { const val = summary.data?.severityCounts?.[key] ?? 0; const total = Math.max(summary.data?.totalAlerts ?? 1, 1); return <div key={key}><div className="mb-1.5 flex justify-between text-xs"><span className="capitalize text-slate-300">{key}</span><span className="font-mono text-slate-500">{val}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${key === 'critical' ? 'bg-rose-400' : key === 'high' ? 'bg-amber-400' : key === 'medium' ? 'bg-sky-400' : 'bg-slate-500'}`} style={{ width: `${Math.max(val / total * 100, val ? 4 : 0)}%` }} /></div></div> })}</div><Link href="/snort" data-testid="link-view-severity-feed" className="mt-6 flex items-center gap-1 text-xs font-bold text-violet-300 hover:text-violet-200">Open alert triage <ArrowUpRight size={14} /></Link></Surface>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]">
      <Surface className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><div className="text-sm font-bold">Latest detections</div><div className="mt-1 text-xs text-slate-500">The newest signal from your sensor</div></div><Link href="/snort" data-testid="link-all-detections" className="text-xs text-violet-300 hover:text-violet-200">View all</Link></div>{alerts.isLoading ? <div className="p-5"><LoadingBlock /></div> : alerts.isError ? <div className="p-5"><ErrorBlock retry={() => alerts.refetch()} /></div> : (alerts.data?.length ?? 0) === 0 ? <div className="p-5"><EmptyBlock title="No detections yet" body="Your local sensor is standing by." /></div> : <div className="divide-y divide-slate-800/70">{alerts.data?.map((alert: any) => <Link href="/snort" key={alert.id} data-testid={`row-alert-${alert.id}`} className="flex items-center justify-between gap-4 px-5 py-3.5 transition hover:bg-slate-800/30"><div className="min-w-0"><div className="truncate text-xs font-semibold text-slate-200">{alert.signature}</div><div className="mt-1 font-mono text-[10px] text-slate-500">{alert.sourceIp} → {alert.destIp} · {formatTime(alert.detectedAt)}</div></div><span className={`shrink-0 rounded-md border px-2 py-1 text-[10px] font-bold uppercase ${severityClass(alert.severity)}`}>{alert.severity}</span></Link>)}</div>}</Surface>
      <Surface className="p-5"><div className="mb-5 flex items-center justify-between"><div><div className="text-sm font-bold">Recent AI insights</div><div className="mt-1 text-xs text-slate-500">Decisions, not just detections</div></div><BrainCircuit size={16} className="text-sky-300" /></div>{insights.isLoading ? <LoadingBlock /> : insights.isError ? <ErrorBlock retry={() => insights.refetch()} /> : (insights.data?.length ?? 0) === 0 ? <EmptyBlock title="No AI insights" body="Analyze an alert to generate the first one." /> : <div className="space-y-3">{insights.data?.map((insight: any) => <div key={insight.id} data-testid={`card-insight-${insight.id}`} className="rounded-xl border border-slate-800 bg-slate-900/45 p-3.5"><div className="flex justify-between gap-3"><div className="text-xs font-bold text-slate-200">{insight.attackType}</div><span className="font-mono text-[10px] text-fuchsia-300">{insight.riskScore}/100</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{insight.analysis}</p></div>)}</div>}</Surface>
    </div>
  </div>;
}
function Metric({ label, value, note, icon: Icon, color }: { label: string; value: string | number; note: string; icon: any; color: string }) { const colors: any = { violet: 'text-violet-300 bg-violet-400/10', rose: 'text-rose-300 bg-rose-400/10', sky: 'text-sky-300 bg-sky-400/10', emerald: 'text-emerald-300 bg-emerald-400/10' }; return <Surface className="p-4"><div className="flex items-center justify-between"><div className={`grid h-8 w-8 place-items-center rounded-lg ${colors[color]}`}><Icon size={16} /></div><span className="font-mono text-[10px] text-slate-600">24H</span></div><div className="mt-5 text-2xl font-extrabold tracking-tight">{value}</div><div className="mt-1 text-xs text-slate-400">{label}</div><div className="mt-2 text-[10px] text-slate-600">{note}</div></Surface>; }